name: coder_up
description: 
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
